#!/usr/bin/env bash

clear
cd ~
sudo mkdir Programs
sudo apt-get update
sudo apt-get autoremove -y
sudo apt-get autoclean -y
sudo apt-get upgrade -y
sudo dpkg --configure -a
sudo apt-get update --fix-missing
sudo apt-get install -f
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install aircrack-ng -y
sudo apt-get install hping3
sudo apt-get install figlet toilet -y
cd ~/Programs/
git clone https://github.com/ZerBea/hcxdumptool.git
cd hcxdumptool
make
make install
cd ~/Programs
git clone https://github.com/ZerBea/hcxtools.git
cd hcxtools﻿
make
make install
sudo apt-get install hashcat -y
cd ~/autoScript
chmod +x autoScript
cd ~
sudo mv autoScript Programs
echo ""
echo "Installation finished"
sleep 1
echo ""
echo "autoScript moved to programs"
sleep 2
echo ""
read -n 1 -r -s -p "Press any key to continue..."
clear
