#!/usr/bin/env bash

clear
cd ~/Programs/autoScript
rm -R autoScript
git clone https://github.com/Treebug842/autoScript-update.git
cd ~/Programs/autoScript/autoScript-update
mv autoScript ~/Programs/autoScript
cd ~/Programs/autoScript
Rm -R autoScript-update
cd ~
clear
