#!/usr/bin/env bash

clear
cd ~/Programs/autoScript
rm -R autoScript
git clone https://github.com/Treebug842/autoScript-update.git
cd ~/Programs/autoScript/autoScript-update
mv autoScript ~/Programs/autoScript
cd ~/Programs/autoScript
rm -R autoScript-update
rm -R update
git clone https://github.com/Treebug842/autoScript-updatefile
cd ~
clear
